name: pytest
on: workflow_dispatch

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: print github action context
        run: echo ${{ github.repositoryUrl }}
      - name: checkout code
        uses: actions/checkout@v3
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
